-- Stage 19: record ADMIN reads of redacted AuditLog projections without
-- introducing unapproved Export persistence or production retention policy.

ALTER TABLE "audit_logs"
  DROP CONSTRAINT "audit_logs_action_type_check",
  ADD CONSTRAINT "audit_logs_action_type_check" CHECK (
    "action_type" IN (
      'AUTHENTICATION_SUCCEEDED', 'AUTHENTICATION_FAILED', 'AUTH_SESSION_REVOKED',
      'USER_PROFILE_UPDATED', 'USER_STATUS_CHANGED',
      'COURSE_CREATED', 'COURSE_UPDATED', 'COURSE_STATUS_CHANGED',
      'CLASS_SECTION_CREATED', 'CLASS_SECTION_UPDATED', 'CLASS_SECTION_CLOSED',
      'COURSE_INVITE_CHANGED', 'ENROLLMENT_CREATED', 'ENROLLMENT_STATUS_CHANGED',
      'ROSTER_IMPORTED', 'ROSTER_ALIGNED', 'ROSTER_RESOLUTION_CHANGED', 'ROSTER_VERSION_ROLLED_BACK',
      'EXERCISE_SESSION_STARTED', 'EXERCISE_SESSION_PAUSED', 'EXERCISE_SESSION_RESUMED',
      'EXERCISE_SESSION_COMPLETED', 'EXERCISE_SESSION_CANCELLED', 'EXERCISE_SESSION_RECONCILED',
      'EXERCISE_SESSION_ENDED', 'EXERCISE_RECORD_DRAFT_CREATED', 'EXERCISE_RECORD_DRAFT_UPDATED',
      'EXERCISE_RECORD_SUBMITTED', 'EXERCISE_RECORD_DISCARDED', 'EXERCISE_RECORD_WITHDRAWN',
      'MEDIA_UPLOAD_INITIATED', 'MEDIA_UPLOAD_CONFIRMED', 'MEDIA_BOUND',
      'MEDIA_PROCESSING_CHANGED', 'MEDIA_DELETED', 'MEDIA_ACCESSED',
      'REVIEW_RESULT_CHANGED', 'SCORE_RULE_CHANGED', 'SCORE_RECALCULATED',
      'SCORE_ADJUSTED', 'SCORE_PUBLISHED', 'SCORE_LOCKED', 'PERMISSION_CHANGED',
      'SYSTEM_MODE_CHANGED', 'DATA_EXPORTED', 'AUDIT_LOG_READ'
    )
  );
