import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { validateEnvironment, type RuntimeConfig } from '../../src/common/config/environment.js';
import { ApplicationError } from '../../src/common/errors/application-error.js';
import { S3MediaStorageAdapter } from '../../src/common/object-storage/s3-media-storage.adapter.js';
import { foundationEnvironment } from '../helpers/test-environment.js';

function runtimeConfig(): RuntimeConfig {
  return validateEnvironment(
    foundationEnvironment('postgresql://test:test@127.0.0.1:1/s3_media_adapter_test', 0),
  ).RUNTIME_CONFIG as RuntimeConfig;
}

describe('S3 media storage key contract', () => {
  it('accepts the exact private key shape generated by MediaService', async () => {
    const adapter = new S3MediaStorageAdapter(runtimeConfig());
    const result = await adapter.createUploadUrl({
      storageKey:
        'media/018f4e2f-8d4b-7c60-a35f-884bd5c9788f/018f4e30-14eb-79db-b7f4-1ac267851e30/video',
      contentType: 'video/mp4',
      contentLength: 250_000_000,
      expiresInSeconds: 300,
    });

    assert.equal(result.method, 'PUT');
    assert.equal(result.requiredHeaders['content-type'], 'video/mp4');
    assert.equal(result.requiredHeaders['content-length'], '250000000');
    assert.equal(new URL(result.url).hostname, 'media-storage.test');
    adapter.onModuleDestroy();
  });

  it('rejects keys with extra path segments before signing', async () => {
    const adapter = new S3MediaStorageAdapter(runtimeConfig());
    await assert.rejects(
      adapter.createUploadUrl({
        storageKey:
          'media/018f4e2f-8d4b-7c60-a35f-884bd5c9788f/exercise_record/018f4e30-14eb-79db-b7f4-1ac267851e30/video',
        contentType: 'video/mp4',
        contentLength: 1,
        expiresInSeconds: 300,
      }),
      (error: unknown) =>
        error instanceof ApplicationError && error.code === 'SYSTEM_DATA_INTEGRITY_ERROR',
    );
  });
});
