-- Add the isolated staging health bootstrap to the closed audit action catalog.
-- Build and validate the expanded constraint before replacing the canonical name.

ALTER TABLE "audit_logs"
  ADD CONSTRAINT "audit_logs_action_type_check_v2" CHECK (
    "action_type" IN (
      'AUTHENTICATION_SUCCEEDED', 'AUTHENTICATION_FAILED', 'AUTH_SESSION_REVOKED',
      'USER_PROFILE_UPDATED', 'USER_STATUS_CHANGED',
      'COURSE_CREATED', 'COURSE_UPDATED', 'COURSE_STATUS_CHANGED',
      'CLASS_SECTION_CREATED', 'CLASS_SECTION_UPDATED', 'CLASS_SECTION_CLOSED',
      'COURSE_INVITE_CHANGED', 'ENROLLMENT_CREATED', 'ENROLLMENT_STATUS_CHANGED',
      'ROSTER_IMPORTED', 'ROSTER_ALIGNED', 'ROSTER_RESOLUTION_CHANGED', 'ROSTER_VERSION_ROLLED_BACK',
      'EXERCISE_SESSION_STARTED', 'EXERCISE_SESSION_PAUSED', 'EXERCISE_SESSION_RESUMED',
      'EXERCISE_SESSION_COMPLETED', 'EXERCISE_SESSION_CANCELLED', 'EXERCISE_SESSION_RECONCILED',
      'EXERCISE_SESSION_ENDED', 'EXERCISE_RECORD_DRAFT_CREATED', 'EXERCISE_RECORD_DRAFT_UPDATED',
      'EXERCISE_RECORD_SUBMITTED', 'EXERCISE_RECORD_DISCARDED', 'EXERCISE_RECORD_WITHDRAWN',
      'MEDIA_UPLOAD_INITIATED', 'MEDIA_UPLOAD_CONFIRMED', 'MEDIA_BOUND',
      'MEDIA_PROCESSING_CHANGED', 'MEDIA_DELETED', 'MEDIA_ACCESSED',
      'REVIEW_RESULT_CHANGED', 'SCORE_RULE_CHANGED', 'SCORE_RECALCULATED',
      'SCORE_ADJUSTED', 'SCORE_PUBLISHED', 'SCORE_LOCKED', 'PERMISSION_CHANGED',
      'SYSTEM_MODE_CHANGED', 'DATA_EXPORTED', 'AUDIT_LOG_READ',
      'AUTH_CHALLENGE_ISSUED', 'AUTH_CREDENTIAL_RECOVERED',
      'NOTIFICATION_CREATED', 'NOTIFICATION_READ', 'PUSH_DEVICE_REGISTERED',
      'PUSH_DEVICE_UNREGISTERED', 'USER_PREFERENCES_UPDATED', 'FEEDBACK_CREATED',
      'EXEMPTION_APPLICATION_CHANGED',
      'LOCATION_POLICY_CHANGED', 'LOCATION_CONSENT_CHANGED', 'LOCATION_TRACK_CHANGED',
      'LOCATION_RETENTION_APPLIED', 'STAGING_FIXTURE_BOOTSTRAP'
    )
  ) NOT VALID;

ALTER TABLE "audit_logs"
  VALIDATE CONSTRAINT "audit_logs_action_type_check_v2";

ALTER TABLE "audit_logs"
  DROP CONSTRAINT "audit_logs_action_type_check";

ALTER TABLE "audit_logs"
  RENAME CONSTRAINT "audit_logs_action_type_check_v2" TO "audit_logs_action_type_check";
